[package]
name = "raft"
version = "0.1.0"
authors = ["dpavlov <dm.pavlov@inbox.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.9.0"
rand = "0.6.5"
futures = "0.3.4"
